### ISSUE TITLE
Crunchyroll

### ISSUE THREAD

**Issue by Nishiki1** [Timeraa/PreMiD#44] opened 2018-12-01 17:10 UTC
**What's the name of the service?**
Ex.  www.crunchyroll.com/ | CrunchyRoll

**What should the Presence display?**
Anime, Episode, time and premium.

**Why do you want support for this service?**
Show the animes i watching, lot of peaple use.

**Are you able to provide an image for the service? (512x512 minimum)**
https://static-s.aa-cdn.net/img/amazon/30600000013157/c1f5bd007387b03512992bfb022b2976

**Comment by Timeraa** [comment] 2018-12-01 17:11
Duplicate of #24 #43 

Will be added, no worries!

**Closed by Timeraa** 2018-12-01 17:11 UTC

**Comment by chuchigod** [comment] 2021-04-25 13:37
crunchyroll recently announced the beta version of the site redesign (beta.crunchyroll.com) which no longer works with premid... please help
![image](https://user-images.githubusercontent.com/79755937/115995586-7434f700-a5f9-11eb-9a6e-01e67b4f178d.png)
